[api]
# This is the page that will be scraped
# You can either point it at a specific page (like part 1 of a walk through)
# or at a group of pages, ie, contains links to all parts of a walkthrough
page_to_scrape = "https://bulbapedia.bulbagarden.net/wiki/Walkthrough:Pok%C3%A9mon_Crystal"

[logging]
logging_level = "DEBUG"
logging_file_name = "pokemon_data_extractor.log"

[db]
#Whether it writes to a files
#placed in the 02_data_folder if true
write_to_file=true

#Pushes it straight to the db
write_to_db=false