import os
import re
import logging

from Config import Config
from DatabaseConfig import Database

class SqlIntegration:
    """ Handles putting data in the db and making sql scripts"""

    def __init__(self):
        self.logger = logging.getLogger(__name__)
        self.write_to_file = Config.get("db", {}).get("write_to_file", True)
        self.write_to_db = Config.get("db", {}).get("write_to_db", False)

    def save_scraped_data_to_db(self, all_milestones, starters, first_boss_lv, game_slug):
        """ Saves the data to the database/makes a sql script
        :param all_milestones: All milestones
        :param starters: The starters
        :param first_boss_lv: The first boss level
        :param game_slug: The game_slug
       """
        self.logger.debug(">> save_scraped_data_to_db")
        # gets the target dir for the paths
        target_dir, start_num = self._prepare_directory()
        slug_parts_sql = ", ".join([f"'{p}'" for p in game_slug.split('-')])

        # starter stage
        starter_milestone = {
            "milestone_name": f"Starter Selection: {', '.join(starters)}",
            "trainers": [],
            "is_starter_stage": True
        }
        all_milestones.insert(0, starter_milestone)

        m_rows, t_rows, team_rows = [], [], []

        # for all the milestones
        for m_idx, milestone in enumerate(all_milestones):
            order_idx = m_idx + 1

            # Generate Milestone SQL Row
            m_row, level_cap = self._generate_milestone_row(milestone, order_idx, slug_parts_sql, game_slug,
                                                            first_boss_lv)
            m_rows.append(m_row)

            # Generate Trainer SQL Rows
            t_rows.extend(self._generate_trainer_rows(milestone, order_idx, game_slug))

            # Generate Team/Pokemon SQL Rows
            team_rows.extend(self._generate_team_rows(milestone, order_idx, game_slug))

        # construct query
        m_sql = (
                f"-- Milestones for {game_slug}\n-- Generated by the PokemonDataExtractor\nINSERT INTO milestones (game_id, stage_name, level_cap, order_index, game_slug)\nVALUES\n    " +
                ",\n    ".join(m_rows) +
                "\nON CONFLICT (game_id, order_index) DO UPDATE SET level_cap = EXCLUDED.level_cap, stage_name = EXCLUDED.stage_name;")

        t_sql = (
                f"-- Trainers for {game_slug}\n-- Generated by the PokemonDataExtractor\nINSERT INTO milestone_trainers (stage_id, trainer_name, is_major_boss)\nVALUES\n    " +
                ",\n    ".join(t_rows) + ";")

        team_sql = (
                f"-- Teams for {game_slug}\n-- Generated by the PokemonDataExtractor\nINSERT INTO milestone_teams (trainer_id, pokemon_slug, slot_number, level, is_ace, moves, condition)\nVALUES\n    " +
                ",\n    ".join(team_rows) + ";")

        # write
        if self.write_to_file:
            self.logger.debug(">> writing to file")
            self._write_files(target_dir, start_num, game_slug, m_sql, t_sql, team_sql)

        # push
        if self.write_to_db:
            self.logger.debug("pushing to db")
            self._push_to_db([m_sql, t_sql, team_sql])

        self.logger.debug("<< save_scraped_data_to_db")


    def _push_to_db(self, sql_scripts):
        """Executes the generated sql on the database directly"""
        conn = None
        try:
            self.logger.info("Pushing data to database...")
            # Use your Database singleton class
            conn = Database.get_connection()
            cur = conn.cursor()

            # Since your Database class sets autocommit=True,
            # we just execute each script.
            for script in sql_scripts:
                cur.execute(script)

            cur.close()
            self.logger.info("Successfully pushed to database")
        except Exception as e:
            # Note: with autocommit=True, rollback won't affect executed statements,
            # but we catch the error for logging purposes.
            self.logger.error(f"Failed to push to database: {e}")

    def _prepare_directory(self):
        """Handles pathing and autoincrementing index logic."""
        base_dir = os.getcwd()
        target_dir = os.path.abspath(os.path.join(base_dir, "..", "database", "queries", "02_data"))
        if not os.path.exists(target_dir):
            os.makedirs(target_dir)

        existing_files = os.listdir(target_dir)
        indices = [int(re.match(r'^(\d+)', f).group(1)) for f in existing_files if re.match(r'^\d+', f)]
        start_num = max(indices) + 1 if indices else 1
        return target_dir, start_num

    def _generate_milestone_row(self, milestone, order_idx, slug_parts_sql, game_slug, first_boss_lv):
        """Logic for the Milestones table and Level Cap calculation.
        :param milestone: the milestone
        :param order_idx: the index of the index
        :param slug_parts_sql: the sql
        :param game_slug: the game slug
        :param first_boss_lv: the first boss level
        :return: the row of sql
        :return level_cap """
        m_name = milestone['milestone_name'].replace("'", "''")

        if milestone.get("is_starter_stage"):
            level_cap = first_boss_lv
        else:
            all_levels = [int(p['level']) for t in milestone.get('trainers', []) for p in t.get('pokemon', []) if
                          p.get('level')]
            level_cap = max(all_levels) if all_levels else first_boss_lv

        row = (f"((SELECT id FROM games WHERE name IN ({slug_parts_sql}) LIMIT 1), "
               f"'{m_name}', {level_cap}, {order_idx}, '{game_slug}')")
        return row, level_cap

    def _generate_trainer_rows(self, milestone, order_idx, game_slug):
        """Logic for the Trainers table (Deduplicated).
        :param milestone: the milestone
        :param order_idx: the index of the index
        :param game_slug: the game_name
        :return: the sql rows of the table"""

        rows = []
        m_name = milestone['milestone_name']
        unique_trainers = []
        seen_names = set()

        for t in milestone.get('trainers', []):
            if t['trainer_name'] not in seen_names:
                unique_trainers.append(t)
                seen_names.add(t['trainer_name'])

        for trainer in unique_trainers:
            t_name = trainer['trainer_name'].replace("'", "''")
            is_boss_area = any(key in m_name for key in ["Gym", "Rival", "Elite Four", "Champion"])
            is_major = "TRUE" if (is_boss_area or trainer.get('is_major_boss')) else "FALSE"

            rows.append(
                f"((SELECT id FROM milestones WHERE game_slug = '{game_slug}' AND order_index = {order_idx} LIMIT 1), "
                f"'{t_name}', {is_major})"
            )
        return rows

    def _generate_team_rows(self, milestone, order_idx, game_slug):
        """Gets the team rows for the milestone.
        :param milestone: the milestone
        :param order_idx: the index of the index
        :param game_slug: the game_name
        :return: the sql rows of the table"""

        rows = []
        for trainer in milestone.get('trainers', []):
            t_name = trainer['trainer_name'].replace("'", "''")
            team = trainer.get('pokemon', [])
            team_max = max([p['level'] for p in team]) if team else 0

            for s_idx, pkmn in enumerate(team):
                is_ace = "TRUE" if (pkmn['level'] == team_max and pkmn['level'] > 0) else "FALSE"
                # Tie-breaker for ace (last pokemon at max level wins)
                if is_ace == "TRUE" and any(p['level'] == team_max for p in team[s_idx + 1:]):
                    is_ace = "FALSE"

                moves_arr = "ARRAY[" + ", ".join([f"'{m}'" for m in pkmn['moves']]) + "]"
                cond_val = trainer.get('condition')
                sql_condition = f"'{cond_val.lower()}'" if cond_val else "NULL"

                rows.append(
                    f"((SELECT id FROM milestone_trainers WHERE trainer_name = '{t_name}' AND stage_id = "
                    f"(SELECT id FROM milestones WHERE game_slug = '{game_slug}' AND order_index = {order_idx} LIMIT 1) LIMIT 1), "
                    f"'{pkmn['pokemon_slug']}', {s_idx + 1}, {pkmn['level']}, {is_ace}, {moves_arr}, {sql_condition})"
                )
        return rows

    def _write_files(self, target_dir, start_num, game_slug, m_sql, t_sql, team_sql):
        """Final file output logic.
        :param target_dir: the target directory
        :param start_num: the start number
        :param game_slug: the game slug
        :param m_sql: the milestone sql
        :param t_sql: the trainer sql
        :param team_sql: the team sql
        """
        file_map = {
            f"{start_num:02}_populate_milestones_{game_slug}.sql": m_sql,
            f"{start_num + 1:02}_populate_trainers_{game_slug}.sql": t_sql,
            f"{start_num + 2:02}_populate_teams_{game_slug}.sql": team_sql
        }
        for filename, content in file_map.items():
            full_path = os.path.join(target_dir, filename)
            with open(full_path, "w", encoding="utf-8") as f:
                f.write(content)
            logging.debug(f"Generated: {filename}")