import psycopg2
from config.config import DB_HOST, DB_NAME, DB_USER, DB_PASS


class DBConnection:
    
    def __init__(self):
        try:
            self.conn = psycopg2.connect(
                host=DB_HOST,
                database=DB_NAME,
                user=DB_USER,
                password=DB_PASS
            )
            self.cursor = self.conn.cursor()
        except psycopg2.Error as e:
            print(f"Error connecting to PostgreSQL: {e}")
            raise

    def close(self):
        self.conn.close()

    def commit(self):
        self.conn.commit()

    def rollback(self):
        self.conn.rollback()

    def get_all_from(self, table):
        """Fetches all names and id from a table.
        :param table: The table to fetch from.
        :return: A dictionary mapping lowercase names to IDs.
        """
        self.cursor.execute(f"SELECT id, name FROM {table}")
        return {name.lower(): id for id, name in self.cursor.fetchall()}

    def insert_pokemon(self, dex_num, name, slug, evolves_from):
        """Inserts a Pokémon into the Pokémon table."""
        self.cursor.execute("""
                            INSERT INTO pokemon (national_dex_number, name, slug, form_name, evolves_from_id)
                            VALUES (%s, %s, %s, %s, %s)
                            ON CONFLICT (national_dex_number, form_name)
                                DO UPDATE SET evolves_from_id = EXCLUDED.evolves_from_id
                            RETURNING id;
                            """, (dex_num, name, slug, '', evolves_from))

        return self.cursor.fetchone()[0]

    def insert_game_stats(self, pokemon_id, ruleset_id, t1, t2, a1, a2, a3):
        """Inserts the Game Stats for different Pokémon."""
        self.cursor.execute("""
                            INSERT INTO pokemon_game_stats
                            (pokemon_id, ruleset_id, type_1_id, type_2_id, ability_1_id, ability_2_id, hidden_ability_id)
                            VALUES (%s, %s, %s, %s, %s, %s,%s)
                            ON CONFLICT (pokemon_id, ruleset_id)
                                DO NOTHING;
                            """, (pokemon_id, ruleset_id, t1, t2, a1, a2, a3))

    def upsert_ability(self, name, description):
        """Inserts an ability and returns its ID. If it exists, returns existing ID."""
        self.cursor.execute("""
                            INSERT INTO abilities (name, description)
                            VALUES (%s, %s)
                                ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
                                                          RETURNING id;
                            """, (name, description))
        return self.cursor.fetchone()[0]
    
                            
    def get_game_id_by_version(self, api_version_id):
        """Maps PokeAPI version ID to your local games.id"""
        self.cursor.execute("SELECT id FROM games WHERE api_version_id = %s", (api_version_id,))
        result = self.cursor.fetchone()
        return result[0] if result else None
    
    def upsert_location(self, api_id, name, region_id):
        self.cursor.execute("""
            INSERT INTO locations (api_id, name, region_id) 
            VALUES (%s, %s, %s)
            ON CONFLICT (api_id) DO UPDATE SET name = EXCLUDED.name
            RETURNING id;
        """, (api_id, name, region_id))
        return self.cursor.fetchone()[0]
    
    def upsert_area(self, api_id, name, location_id):
        self.cursor.execute("""
            INSERT INTO location_areas (api_id, name, location_id) 
            VALUES (%s, %s, %s)
            ON CONFLICT (api_id) DO UPDATE SET name = EXCLUDED.name
            RETURNING id;
        """, (api_id, name, location_id))
        return self.cursor.fetchone()[0]
    
    def insert_encounter(self, game_id, location_id, area_id, pokemon_id, method, max_level, min_level):
        self.cursor.execute("""
            INSERT INTO encounters (
                game_id, location_id, pokemon_id, method, max_level, min_level
            )
            VALUES (%s, %s, %s, %s, %s, %s, %s)
            ON CONFLICT (game_id, location_id, pokemon_id, method) 
            DO UPDATE SET 
                max_level = GREATEST(encounters.max_level, EXCLUDED.max_level),
                min_level = LEAST(encounters.min_level, EXCLUDED.min_level);
        """, (game_id, location_id, area_id, pokemon_id, method, max_level, min_level))
        
        
    def upsert_game(self, name, ruleset_id, api_version_id, region_id):
        """Inserts a game into the games table.
        :param name: The name of the game.
        :param ruleset_id: The ruleset ID for the game.
        :param api_version_id: The API version ID for the game. This is generated by PokeAPI
        :param: region_id: The region ID for the game. """
        self.cursor.execute("""
            INSERT INTO games (name, ruleset_id, api_version_id,region_id) 
            VALUES (%s, %s, %s, %s)
            ON CONFLICT (api_version_id) DO UPDATE SET name = EXCLUDED.name
            RETURNING id;
        """, (name, ruleset_id, api_version_id,region_id))
        return self.cursor.fetchone()[0]