FROM postgres:18

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        python3 \
        python3-pip \
        build-essential \
        libpq-dev \
    && rm -rf /var/lib/apt/lists/*
    
# ... Python Libraries ...
RUN pip3 install --break-system-packages psycopg2-binary requests dotenv

COPY ./queries/init_db.sh /docker-entrypoint-initdb.d/

ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]

CMD ["postgres"]