FROM postgres:18

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        python3 \
        python3-dev \
        python3-pip \
        build-essential \
        libpq-dev \
    && rm -rf /var/lib/apt/lists/*
    
    
COPY pokemon_data_loader/requirements.txt /tmp/requirements.txt
COPY database/queries/init_db.sh /docker-entrypoint-initdb.d/

RUN pip3 install --break-system-packages -r /tmp/requirements.txt


ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]

CMD ["postgres"]